signaux-faibles/prepare-import

main.go, main_test.go
...following this morning's pairing session.
See the list of commits to see the steps I followed.
My intent was to make it possible and easy to review the diff of each step individually.
Review recommendation: As I reformatted the code (thanks to a plug-in for my IDE that runs `gofmt` every time I save a go file), feel free to ignore the resulting diff by disabling the whitespace diff, from GitHub's PR interface.
Possible next steps:
- See "Table-driven tests using subtests" from [Using Subtests and Sub-benchmarks - The Go Blog](https://blog.golang.org/subtests)
- Use `assert` helpers provided by [stretchr/testify: A toolkit with common assertions and mocks that plays nicely with the standard library](https://github.com/stretchr/testify/#assert-package) (recommended by Anthony Seure)
=> Fix + refactor tests for PopulateFilesProperty

main.go, main_test.go
Ajoute le support de plusieurs fichiers de données réels:
```
"diane_req_2002.csv",              // --> "diane"
"diane_req_dom_2002.csv",          // --> "diane"
"effectif_dom.csv",                // --> "effectif"
"filter_siren_2002.csv",           // --> "filter"
"sireneUL.csv",                    // --> "sirene_ul"
"StockEtablissement_utf8_geo.csv", // --> "comptes"
```
Et intègre une nouvelle manière de définir des tests: table-based.
=> Feat: Prendre en charge fichiers csv courants

main.go, main_test.go
J'ai deviné le types de la plupart des fichiers `bin` présents dans le dossier `/var/lib/goup_base/public/2002` du serveur `stockage`, à partir des métadonnées fournies dans les fichiers `info` correspondants, et la table fournie dans la section suivante de la documentation: https://github.com/signaux-faibles/documentation/blob/master/processus-traitement-donnees.md#sp%C3%A9cificit%C3%A9s-de-limport.
Avant de fusionner cette PR:
- vérifier que les mappings devinés sont corrects
- quel est le type du fichier `Sigfaible_etablissement_utf8.csv` ?
- comment reconnaitre les fichiers de type `dpae` et `dmmo` ?
=> feat: Reconnaissance de certains fichiers reçus par goup

main.go, main_test.go
Changements basés sur revue de https://github.com/signaux-faibles/prepare-import/pull/10:
- correction des types pour `Sigfaible_etablissement_utf8.csv`, `Sigfaible_effectif_siret.csv` et `Sigfaible_effectif_siren.csv`
- Retrait de récursion => `GetFileType()` ne prend plus de `Reader()` en paramètre => la responsabilité de lire les métadonnées revient à `PopulateFilesProperty()`
- Vu que `PurePrepareImport()` appelle `PopulateFilesProperty()`, qui repose sur le système de fichiers pour lire les métadonnées, `PurePrepareImport()` n'est au final plus une fonction pure. => voir si on peut extraire les appels au système de fichiers afin de rendre cette fonction à nouveau pure.
- sérialiser le résultat de `./prepare-import` au format JSON.
=> fix: Correction des types incorrects + Retrait de récursion

main.go, main_test.go, signauxfaiblesTypes.go
Création d'une interface `DataFile`, qui contient une méthode `DetectFileType`
=> refactor: Rerendre pures les fonctions pures + nommage + séparation fichier

Makefile, main.go, main_test.go, signauxfaiblesTypes.go
cf https://github.com/signaux-faibles/prepare-import/pull/12/files#r401497105
... et en bonus: un Makefile qui fournit notamment une commande pour (re)formatter le code.
```sh
$ make format
```
=> refactor: réduction de complexité + commentaires

main.go, main_test.go
- PurePrepareImport retourne les noms de fichiers non supportés, quand c'est le cas (Note: à afficher depuis le script)
- LoadMetadata ne retourne plus d'erreurs, il panique
- Factorisation de TestPrepareImport
- Ajout de test en cas de fichier .bin sans metadata (.info)
- la commande `prepare-import` devrait retourner la liste des fichiers non supportés, dans la sortie d'erreurs (stderr)
=> feat: Gestion d'erreurs

.github/workflows/go.yml
References:
- https://deepsource.io/gh/signaux-faibles/prepare-import/settings/reporting
- https://deepsource.io/docs/analyzer/test-coverage.html#configuration-artifacts
- https://github.com/signaux-faibles/prepare-import/settings/secrets
- https://deepsource.io/docs/how-to/add-go-cov-ci.html#with-circle-ci
=> fix: envoi de couverture de tests à DeepSource

main.go, main_test.go
- les fichiers `.info` était remontés comme fichiers non supportés
- `PopulateFilesProperty()` comptait un tableau vide de fichiers non supportés comme une erreur
=> fix: Faux positifs sur remontée de fichiers non supportés

.github/workflows/go.yml, README.md, end_to_end_golden.txt, end_to_end_test.go, main.go, main_test.go
* Ajout d'un test de bout en bout pour `prepare-import` à l'aide d'un golden file. 
* Amélioration et documentation du makefile
* Correction de `createTempFiles`
* `prepare-import` affiche le JSON même si certains fichiers ne sont pas supportés
=> feat(tests): Ajout d'un test de bout en bout

end_to_end_golden.txt, end_to_end_test.go, main.go, main_test.go, signauxfaiblesTypes.go
- Introduction du type `ValidFileType` avec des constantes
- Renommage de `PurePrepareImport` en `PopulateAdminObject`
- Correction: type `COMPTES` --> `SIRENE`
=> feat: génération des propriétés `_id` et `complete_types`

main.go, main_test.go
Cf https://github.com/signaux-faibles/prepare-import/pull/26#issuecomment-615194913.
Description de l'avertissement reporté par Codacy:
- exported `func BatchKey` returns unexported type `main.batchKeyType`, which can be annoying to use
```go
func BatchKey(key string) (batchKeyType, error) {
```
=> refactor: Correction de l'avertissement "unexported-return"

go.mod, go.sum
Suite à la lecture de [Using Go Modules - The Go Blog](https://blog.golang.org/using-go-modules), comme suggéré via Twitter: https://twitter.com/rumpl/status/1252591500631867392
Si j'ai bien compris, cette manipulation permet:
- de bénéficier du suivi sécurisé des dépendances par Go;
- et de placer son dépot local ailleurs que dans le GOPATH.
Je teste cette transition ici pour commencer, et la proposerai ensuite sur `opensignauxfaibles`.
=> feat: Définition d'un module Go

end_to_end_golden.txt, end_to_end_test.go, main.go, main_test.go, signauxfaiblesTypes.go
Fixes #32.
Désormais, les fichiers de données "bin" (associés à un fichier `.info`) n'ont plus d'extension.
=> fix(#32): Les fichiers *.bin n'ont plus d'extension

end_to_end_golden.txt, end_to_end_golden_err.txt, end_to_end_test.go, main.go, main_test.go
Fixes #31.
- Les fichiers listés dans la propriété `files` résultante de l'appel à `prepare-import` sont préfixés par leur répertoire de batch. Ex: `/numero_batch/nom_fichier.csv`.
- Le paramètre `--path` attend le chemin du répertoire parent contenant un sous-répertoire par batch.
=> fix(#31): Les chemins d'accès de la propriété files doivent inclure le numéro de batch

.github/semantic.yml
Pour éviter l'erreur "PR has only one non-merge commit and it's not semantic" quand on soumet une PR GitHub ne contenant qu'un sel commit dont le message n'est pas un "conventional commit". Observée dans PR #36, et celle-ci.
Sachant qu'on fusionne nos PRs en "squashant" ses commits, seul le titre de la PR a besoin d'être un "conventional commit", au final.
=> fix(github): "PR has only one non-merge commit and it's not semantic"

createfilter/UrssafToPeriod.go, createfilter/main.go, createfilter/main_test.go, prepareimport/adminobject.go, prepareimport/adminobject_test.go, prepareimport/filesproperty.go, prepareimport/filesproperty_test.go, prepareimport/prepareimport.go, prepareimport/prepareimport_test.go, tools/procedure_import.md
Suite de PR #42.
- réfléchir à comment ne plus avoir à spécifier `date_fin_effectif` lors de la création de sous-batch, cf https://github.com/signaux-faibles/prepare-import/pull/42#discussion_r520745704
=> fix: Fin d'intégration de la détection de date_fin_effectif + refactoring

end_to_end_golden_err.txt, main.go, prepareimport/adminobject_test.go, prepareimport/batchkey.go, prepareimport/batchkey_test.go, prepareimport/filesproperty.go, prepareimport/filesproperty_test.go, prepareimport/prepareimport.go, prepareimport/prepareimport_test.go
Suite de PR #42. Contribue à https://github.com/signaux-faibles/opensignauxfaibles/issues/167.
Pour importer un sous-batch (c.a.d. un ensemble de fichiers de données basé sur le même périmètre/filtre que le précédent import), il faut ajouter à la main le fichier `filter` + la date de fin effectif employés lors du précédent import. Au delà d'être pénible, le fait d'effectuer cette opération à la main augmente le risque de mauvaise manipulation, et donc d'altération/perte de données dans la base de production.
Supposons la hiérarchie suivante de répertoires batches:
```
|
|-- batches
|     |-- 1802
|     |-- 1802
|     |    |-- 1802_01
```
Désormais, depuis le répertoire `batches`, on peut appeler:
```sh
$ prepare-import --batch 1802 # ... puis ...
$ prepare-import --batch 1802_01
```
=> …
=> feat: Réutiliser les fichiers effectifs et filtre dans les sous-batches

.github/workflows/go.yml, createfilter/main.go, createfilter/main_test.go
Contribue à https://github.com/signaux-faibles/opensignauxfaibles/issues/199.
En écrivant un test unitaire, je me suis rendu compte que la valeur `75` – rattachée à la colonne dep, comme _département_ – était considérée comme valeur d’effectif ≥10.
Si ce bug est avéré, il est probable que nous ayons importé plus de petites entreprises que voulu.
=> fix(createfilter): Ne pas considérer le département comme valeur d'effectif

createfilter/main.go, createfilter/main_test.go
En investiguant des erreurs de parsing de `cotisations` (ce qui m'a fait remonter jusqu'au filtre de périmètre), je me suis rendu compte que notre dernier filtre contenait plusieurs fois le même SIREN !
Cette amélioration propose de dé-dupliquer les numéros SIREN en sortie de la création de périmètre.
=> fix(filter): Dé-duplication des SIRENs dans le filtre/périmètre

prepareimport/filetypes.go, prepareimport/filetypes_test.go
Suite de https://github.com/signaux-faibles/opensignauxfaibles/pull/310.
=> feat: Reconnaissance de l'extension .gz pour les fichiers urssaf

createfilter/main.go
Lors d'une intégration j'ai rencontré un fichier qui m'a provoqué l'erreur suivante:
```
/home/centos/prepare-import/prepare-import -batch 2101
Listing data files in 2101/ ...
Found effectif file: 083fe617e80f2e30a21598d38a854bc6
Generating filter file: /2101/filter_siren_2101.csv ...
panic: runtime error: slice bounds out of range [:9] with length 0
goroutine 1 [running]:
github.com/signaux-faibles/prepare-import/createfilter.outputPerimeter(0xc0000f6120, 0x56aac0, 0xc0000a8108, 0x64, 0xa, 0x3)
/home/centos/prepare-import/createfilter/main.go:96 +0x3af
github.com/signaux-faibles/prepare-import/createfilter.CreateFilter(0x56aac0, 0xc0000a8108, 0xc0000a7290, 0x25, 0x64, 0xa, 0x2, 0x0, 0x0)
/home/centos/prepare-import/createfilter/main.go:66 +0x14d …
```
=> fix: skip lines with empty siret during effectif filter

createfilter/UrssafToPeriod.go, createfilter/main.go, prepareimport/filesproperty.go, prepareimport/prepareimport.go, prepareimport/prepareimport_test.go
Lorsqu'on exécute `prepare-import` dans un répertoire dans lequel le fichier effectif est compressé, une erreur `open /somedir/gzip:/1802/719776012f6a124c3fab0f1c74fd585a: no such file or directory` empêche la création du filtre, causant une erreur d'importation dans `sfdata`: https://github.com/signaux-faibles/opensignauxfaibles/issues/354.
- Assurer que le préfixe `gzip:` est toujours en début de chemin, même après constitution du chemin absolu.
- Étendre le support du préfixe `gzip:` à `createfilter`.
- Corrections d'avertissements de linter.
- Déduplication du code de certains tests.
=> fix: Création de filtre à partir d'un fichier effectif compressé
